const translations = {
  en: {
    "announce": "🍁 Tax Season 2025 — File your T1 before April 30.",
    "book_announce": "Book your appointment →",
    "nav_services": "Services",
    "nav_tools": "Tools",
    "nav_calc": "Tax Calculator",
    "nav_about": "About",
    "nav_contact": "Contact",
    "nav_book": "Book Appointment",
    "hero_badge": "Trusted in Toronto GTA since 2017",
    "hero_title": "<em>Quick & Effective</em><br>Accounting<br>Solutions",
    "hero_desc": "Professional accounting, bookkeeping, and tax services for individuals and businesses in North York, Toronto, and Montreal. Serving clients in English, Turkish, Bosnian, and Albanian.",
    "btn_book_free": "📅 Book Free Consultation",
    "btn_try_calc": "🧮 Try Tax Calculator",
    "stat_exp": "Years Experience",
    "stat_lang": "Languages Supported",
    "stat_clients": "Happy Clients",
    "card_personal": "Personal Tax Returns",
    "card_personal_desc": "T1, T4, self-employed, Uber drivers, non-residents, students and retirees.",
    "card_personal_tag": "Starting from $80",
    "card_biz": "Business Registration & Corporate Tax",
    "card_biz_desc": "Incorporation, GST/HST registration, payroll setup, T2 returns and full bookkeeping.",
    "card_biz_tag": "Free Initial Consult",
    "card_multi": "Multilingual Support",
    "card_multi_desc": "Serving Turkish, Bosnian and Albanian communities in the GTA with no language barrier.",
    "trust_cra": "CRA Certified<br>Accountants",
    "trust_same": "Same-Day<br>Appointments",
    "trust_4lang": "4 Languages<br>Supported",
    "trust_secure": "Secure Document<br>Upload Portal",
    "trust_wa": "WhatsApp<br>Support",
    "sec_services": "Our Services",
    "title_services": "Everything you need,<br>under one roof",
    "desc_services": "From personal T1 returns to corporate filings and business registration — expert accounting for every stage of your financial life.",
    "serv_pers": "Personal Services",
    "serv_pers_1": "Employed (T4)",
    "serv_pers_2": "Self-Employed",
    "serv_pers_3": "Individual (T1)",
    "serv_pers_4": "Non-Residents",
    "serv_pers_5": "Retired",
    "serv_pers_6": "Student",
    "serv_pers_7": "Social Assistance Recipients",
    "serv_pers_8": "Uber / Gig Economy Driver",
    "serv_bizreg": "Business Registration",
    "serv_bizreg_1": "Incorporation Registration",
    "serv_bizreg_2": "Business Name Search (NUANS)",
    "serv_bizreg_3": "GST/HST Number Registration",
    "serv_bizreg_4": "Payroll Registration",
    "serv_bizreg_5": "Sole Proprietorship",
    "serv_bizreg_6": "Business Dissolution",
    "serv_biz": "Business Services",
    "serv_biz_1": "Accounting",
    "serv_biz_2": "Bookkeeping",
    "serv_biz_3": "Income Tax",
    "serv_biz_4": "Corporate Tax (T2)",
    "serv_biz_5": "Payroll Management",
    "serv_biz_6": "Business Mailbox",
    "sec_tools": "Platform Features",
    "title_tools": "Smart tools for<br>effortless accounting",
    "desc_tools": "A modern platform with tools that save you time, answer your questions 24/7, and keep your documents secure.",
    "badge_avail": "Available Now",
    "badge_updated": "Updated",
    "badge_new": "New",
    "badge_soon": "Coming Soon",
    "tool_book": "Online Appointment Booking",
    "tool_book_desc": "Book a consultation any time. Choose your service, pick a time slot, and get instant email confirmation.",
    "tool_calc": "Tax Estimator Calculator",
    "tool_calc_desc": "Instant estimate of your federal and Ontario provincial taxes. Now with RRSP and Capital Gains.",
    "tool_chat": "AI Chat Assistant",
    "tool_chat_desc": "Ask any tax question 24/7. Try the mock assistant below to get instant answers about tax deadlines and rates.",
    "tool_gst": "GST/HST Calculator",
    "tool_gst_desc": "Instantly add or extract 13% Ontario HST from any amount. Perfect for invoicing and expense tracking.",
    "tool_doc": "Secure Document Portal",
    "tool_doc_desc": "Upload T4s, receipts, and invoices through our encrypted portal. No more sending documents by email.",
    "tool_remind": "CRA Deadline Reminders",
    "tool_remind_desc": "Never miss a filing date. Subscribe for automatic T1, T2, and GST/HST deadline reminders to your inbox.",
    "sec_calc": "Tax Estimator",
    "title_calc": "Estimate your<br>2024 tax return",
    "desc_calc": "Get a quick estimate of your income tax. For a precise result tailored to your situation, book a free consultation.",
    "calc_bullet_1": "Federal + Ontario Provincial Tax",
    "calc_bullet_2": "Basic personal amount deductions",
    "calc_bullet_3": "Employment and self-employed income",
    "calc_bullet_4": "Results in seconds, no login required",
    "calc_box_title": "🧮 Quick Tax Estimate — 2024",
    "calc_lbl_income": "Annual Income (Gross)",
    "calc_lbl_rrsp": "RRSP Contribution ($)",
    "calc_lbl_cap": "Capital Gains ($)",
    "calc_lbl_emp": "Employment Type",
    "emp_opt_1": "Employed (T4)",
    "emp_opt_2": "Self-Employed",
    "emp_opt_3": "Uber / Gig Worker",
    "calc_lbl_prov": "Province",
    "calc_res_lbl": "Estimated Tax Owing",
    "calc_res_note": "Effective rate",
    "calc_cta_note": "Want the exact number?",
    "gst_title": "📊 Ontario GST/HST Calculator",
    "gst_desc": "Quickly add or extract 13% HST for your invoices or receipts in Ontario.",
    "gst_amt": "Amount ($)",
    "btn_add_hst": "Add 13% HST",
    "btn_ext_hst": "Extract 13% HST",
    "gst_sub": "Subtotal:",
    "gst_tax": "HST (13%):",
    "gst_tot": "Total:",
    "gst_biz_tag": "For Businesses",
    "gst_biz_title": "Invoicing made<br>simple",
    "gst_biz_desc": "If your business revenue exceeds $30,000 in a calendar quarter or over four consecutive calendar quarters, you must register for and collect GST/HST.",
    "gst_biz_1": "Ontario HST Rate is 13%",
    "gst_biz_2": "GST is 5%, Provincial portion is 8%",
    "gst_biz_3": "We handle GST/HST return filings",
    "btn_gst_help": "Need help registering? →",
    "sec_book": "Online Booking",
    "title_book": "Book your appointment<br>in 60 seconds",
    "desc_book": "Choose your service, select a convenient time, and we'll confirm instantly — in-person at our North York office or via video call.",
    "step_1_title": "Choose your service",
    "step_1_desc": "T1, T2, bookkeeping, business registration and more.",
    "step_2_title": "Pick a time slot",
    "step_2_desc": "Available Mon–Sat, 9am–6pm. Same-day slots often available.",
    "step_3_title": "Get confirmed instantly",
    "step_3_desc": "Confirmation email with office address or video link sent right away.",
    "loc_title": "📍 Office Location",
    "book_box_title": "📅 Request an Appointment",
    "lbl_name": "Full Name",
    "lbl_phone": "Phone",
    "lbl_email": "Email",
    "lbl_serv": "Service Needed",
    "lbl_date": "Preferred Date",
    "lbl_time": "Time",
    "lbl_meet": "Meeting Type",
    "btn_confirm": "Confirm Appointment →",
    "book_wa": "Or reach us on WhatsApp",
    "sec_test": "Client Reviews",
    "title_test": "Trusted by hundreds<br>across the GTA",
    "desc_test": "Real feedback from individuals and business owners who trust Face Accounting year after year.",
    "test_1": "\"I've been filing my T1 with Face Accounting for 3 years. As a self-employed consultant my taxes are complicated — they always get me the best refund possible.\"",
    "test_2": "\"They handled our incorporation, GST registration, and first corporate tax return. Everything was smooth and professional. Great service!\"",
    "test_3": "\"As an Uber driver I never knew how to file taxes correctly. Face Accounting explained everything clearly and filed everything on time. Highly recommended!\"",
    "test_1_sub": "Self-Employed, North York",
    "test_2_sub": "Business Owner, Toronto",
    "test_3_sub": "Uber Driver, Mississauga",
    "about_badge_lbl": "Years Serving Toronto GTA",
    "sec_about": "About Us",
    "title_about": "A firm you can<br>truly trust",
    "desc_about_1": "Our professional services firm in North York has been providing dedicated, quality accounting services to individuals and businesses since 2017.",
    "desc_about_2": "We understand entrepreneurs are busy. Our job is to handle your taxes and bookkeeping so you can focus on growing your business — across North York, Toronto GTA, and Montreal.",
    "about_comm": "Communities we proudly serve:",
    "btn_book_about": "Book Free Consultation →",
    "sec_cont": "Contact Us",
    "title_cont": "Get in touch<br>anytime",
    "cont_addr": "Office Address",
    "cont_phone": "Phone",
    "cont_email": "Email",
    "cont_wa": "WhatsApp",
    "cont_pref_lang": "Preferred Language:",
    "cont_box": "Send us a message",
    "cont_subj": "Subject",
    "cont_msg": "Message",
    "btn_send": "Send Message →",
    "footer_rights": "© 2025 FaceAccounting.com — All rights reserved. Serving Toronto GTA & Montreal.",
    "footer_addr": "1110 Finch Ave W, Unit 314, North York ON",
    "modal_title": "Booking Confirmed!",
    "modal_desc": "Thank you. Your appointment has been requested successfully. We will send a confirmation email with details shortly.",
    "btn_done": "Done",
    "chat_title": "🤖 FaceTax Assistant",
    "chat_greet": "Hi there! 👋 I'm your AI Tax Assistant. How can I help you today?",
    "chat_q1": "Tax Deadline?",
    "chat_q2": "HST Rate?",
    "chat_q3": "Pricing?",
    "chat_q4": "T1 Requirements?"
  },
  tr: {
    "announce": "🍁 2025 Vergi Sezonu — T1 beyannamenizi 30 Nisan'dan önce verin.",
    "book_announce": "Randevunuzu alın →",
    "nav_services": "Hizmetler",
    "nav_tools": "Araçlar",
    "nav_calc": "Vergi Hesaplayıcı",
    "nav_about": "Hakkımızda",
    "nav_contact": "İletişim",
    "nav_book": "Randevu Al",
    "hero_badge": "2017'den beri Toronto GTA'da Güvenilir",
    "hero_title": "<em>Hızlı & Etkili</em><br>Muhasebe<br>Çözümleri",
    "hero_desc": "North York, Toronto ve Montreal'de bireyler ve işletmeler için profesyonel muhasebe, defter tutma ve vergi hizmetleri. İngilizce, Türkçe, Boşnakça ve Arnavutça dillerinde hizmet veriyoruz.",
    "btn_book_free": "📅 Ücretsiz Danışmanlık Al",
    "btn_try_calc": "🧮 Hesaplayıcıyı Dene",
    "stat_exp": "Yıllık Tecrübe",
    "stat_lang": "Hizmet Verilen Dil",
    "stat_clients": "Mutlu Müşteri",
    "card_personal": "Bireysel Vergi Beyannameleri",
    "card_personal_desc": "T1, T4, serbest çalışanlar, Uber sürücüleri, öğrenciler ve emekliler.",
    "card_personal_tag": "$80'dan başlayan fiyatlarla",
    "card_biz": "Şirket Kurulumu & Kurumlar Vergisi",
    "card_biz_desc": "Şirket kuruluşu, GST/HST kaydı, bordro kurulumu, T2 beyannameleri ve defter tutma.",
    "card_biz_tag": "Ücretsiz İlk Görüşme",
    "card_multi": "Çok Dilli Destek",
    "card_multi_desc": "GTA'da Türkçe, Boşnakça ve Arnavutça konuşan topluluklara dil bariyeri olmadan hizmet veriyoruz.",
    "trust_cra": "CRA Onaylı<br>Muhasebeciler",
    "trust_same": "Aynı Gün<br>Randevu",
    "trust_4lang": "4 Dilde<br>Destek",
    "trust_secure": "Güvenli Belge<br>Yükleme Portalı",
    "trust_wa": "WhatsApp<br>Desteği",
    "sec_services": "Hizmetlerimiz",
    "title_services": "İhtiyacınız olan her şey,<br>tek çatı altında",
    "desc_services": "Kişisel T1 beyannamelerinden şirket kurulumlarına kadar finansal hayatınızın her aşaması için uzman muhasebe.",
    "serv_pers": "Bireysel Hizmetler",
    "serv_pers_1": "Maaşlı Çalışan (T4)",
    "serv_pers_2": "Serbest Çalışan (Self-Employed)",
    "serv_pers_3": "Bireysel Beyanname (T1)",
    "serv_pers_4": "Kanada'da İkamet Etmeyenler",
    "serv_pers_5": "Emekli",
    "serv_pers_6": "Öğrenci",
    "serv_pers_7": "Sosyal Yardım Alanlar",
    "serv_pers_8": "Uber / Gig Ekonomisi Sürücüsü",
    "serv_bizreg": "İşletme Kaydı",
    "serv_bizreg_1": "Şirket (Incorporation) Kurulumu",
    "serv_bizreg_2": "İsim Tescili (NUANS)",
    "serv_bizreg_3": "GST/HST Numara Kaydı",
    "serv_bizreg_4": "Bordro (Payroll) Kaydı",
    "serv_bizreg_5": "Şahıs Şirketi (Sole Proprietorship)",
    "serv_bizreg_6": "Şirket Kapanışı",
    "serv_biz": "Kurumsal Hizmetler",
    "serv_biz_1": "Muhasebe Danışmanlığı",
    "serv_biz_2": "Defter Tutma (Bookkeeping)",
    "serv_biz_3": "Gelir Vergisi",
    "serv_biz_4": "Kurumlar Vergisi (T2)",
    "serv_biz_5": "Bordro Yönetimi",
    "serv_biz_6": "İşletme Posta Kutusu",
    "sec_tools": "Platform Özellikleri",
    "title_tools": "Zahmetsiz muhasebe için<br>akıllı araçlar",
    "desc_tools": "Zaman kazandıran, 7/24 sorularınızı yanıtlayan ve belgelerinizi güvende tutan modern bir platform.",
    "badge_avail": "Kullanımda",
    "badge_updated": "Güncellendi",
    "badge_new": "Yeni",
    "badge_soon": "Çok Yakında",
    "tool_book": "Online Randevu Sistemi",
    "tool_book_desc": "İstediğiniz zaman randevu alın. Hizmetinizi seçin, saatinizi belirleyin ve anında e-posta onayı alın.",
    "tool_calc": "Vergi Hesaplayıcı",
    "tool_calc_desc": "Federal ve Ontario eyalet vergilerinizin anlık tahmini. Artık RRSP ve Sermaye Kazancı dahil.",
    "tool_chat": "Yapay Zeka Asistan",
    "tool_chat_desc": "7/24 her türlü vergi sorunuzu sorun. Aşağıdaki asistanı deneyin.",
    "tool_gst": "GST/HST Hesaplayıcı",
    "tool_gst_desc": "Herhangi bir tutara %13 Ontario HST ekleyin veya çıkarın. Faturalandırma için mükemmel.",
    "tool_doc": "Güvenli Belge Portalı",
    "tool_doc_desc": "T4'lerinizi, makbuzlarınızı şifreli portalımız üzerinden yükleyin. E-postaya son.",
    "tool_remind": "CRA Tarih Hatırlatıcı",
    "tool_remind_desc": "T1, T2 ve GST/HST son başvuru tarihleri için otomatik e-posta hatırlatıcıları.",
    "sec_calc": "Vergi Hesaplayıcı",
    "title_calc": "2024 Vergi İadenizi<br>Tahmin Edin",
    "desc_calc": "Gelir verginizin hızlı bir tahminini alın. Size özel kesin bir sonuç için ücretsiz randevu alın.",
    "calc_bullet_1": "Federal + Ontario Eyalet Vergisi",
    "calc_bullet_2": "Temel kişisel indirimler",
    "calc_bullet_3": "Maaşlı ve serbest meslek geliri",
    "calc_bullet_4": "Saniyeler içinde sonuç, üyelik gerekmez",
    "calc_box_title": "🧮 Hızlı Vergi Tahmini — 2024",
    "calc_lbl_income": "Yıllık Gelir (Brüt)",
    "calc_lbl_rrsp": "RRSP Katkısı ($)",
    "calc_lbl_cap": "Sermaye Kazancı ($)",
    "calc_lbl_emp": "Çalışma Şekli",
    "emp_opt_1": "Maaşlı (T4)",
    "emp_opt_2": "Serbest Çalışan",
    "emp_opt_3": "Uber Sürücüsü",
    "calc_lbl_prov": "Eyalet",
    "calc_res_lbl": "Tahmini Ödenecek Vergi",
    "calc_res_note": "Efektif oran",
    "calc_cta_note": "Kesin rakamı mı istiyorsunuz?",
    "gst_title": "📊 Ontario GST/HST Hesaplayıcı",
    "gst_desc": "Ontario'daki faturalarınız veya fişleriniz için %13 HST'yi hızlıca ekleyin veya çıkarın.",
    "gst_amt": "Tutar ($)",
    "btn_add_hst": "%13 HST Ekle",
    "btn_ext_hst": "%13 HST Çıkar",
    "gst_sub": "Ara Toplam:",
    "gst_tax": "HST (%13):",
    "gst_tot": "Toplam:",
    "gst_biz_tag": "İşletmeler İçin",
    "gst_biz_title": "Faturalandırma artık<br>çok kolay",
    "gst_biz_desc": "Eğer işletmenizin geliri üst üste 4 çeyrekte 30,000 doları aşıyorsa, GST/HST numarası almak zorundasınız.",
    "gst_biz_1": "Ontario HST Oranı %13'tür",
    "gst_biz_2": "Bunun %5'i GST, %8'i Eyalet vergisidir",
    "gst_biz_3": "GST/HST beyannamelerinizi biz hallederiz",
    "btn_gst_help": "Kayıt için yardım mı lazım? →",
    "sec_book": "Online Randevu",
    "title_book": "Randevunuzu 60<br>saniyede alın",
    "desc_book": "Hizmetinizi seçin, uygun saati belirleyin ve anında onaylayalım — ister ofisimizde, ister görüntülü.",
    "step_1_title": "Hizmetinizi Seçin",
    "step_1_desc": "T1, T2, defter tutma, şirket kurulumu ve dahası.",
    "step_2_title": "Saat Belirleyin",
    "step_2_desc": "Pzt–Cmt, 09:00–18:00 arası müsaitiz. Genellikle aynı gün randevu bulunur.",
    "step_3_title": "Anında Onay Alın",
    "step_3_desc": "Ofis adresi veya video linki anında e-postanıza gelsin.",
    "loc_title": "📍 Ofis Lokasyonu",
    "book_box_title": "📅 Randevu Talebi Oluştur",
    "lbl_name": "Ad Soyad",
    "lbl_phone": "Telefon",
    "lbl_email": "E-posta",
    "lbl_serv": "İstenen Hizmet",
    "lbl_date": "Tercih Edilen Tarih",
    "lbl_time": "Saat",
    "lbl_meet": "Görüşme Tipi",
    "btn_confirm": "Randevuyu Onayla →",
    "book_wa": "Veya bize WhatsApp'tan ulaşın",
    "sec_test": "Müşteri Yorumları",
    "title_test": "GTA'da yüzlerce<br>kişinin güveni",
    "desc_test": "Her yıl Face Accounting'e güvenen bireyler ve işletme sahiplerinin gerçek geri bildirimleri.",
    "test_1": "\"T1 beyannamemi 3 yıldır Face Accounting ile yapıyorum. Serbest çalışan bir danışman olarak vergilerim karmaşıktır ama her zaman en iyi iadeyi almamı sağlarlar.\"",
    "test_2": "\"Şirket kurulumumuzu ve ilk kurumlar vergimizi hallettiler. Her şey çok pürüzsüzdü. Türkçe hizmet vermeleri de harika!\"",
    "test_3": "\"Bir Uber sürücüsü olarak vergileri nasıl doğru yapacağımı bilmiyordum. Her şeyi netçe anlattılar. Kesinlikle tavsiye ederim!\"",
    "test_1_sub": "Serbest Çalışan, North York",
    "test_2_sub": "İşletme Sahibi, Toronto",
    "test_3_sub": "Uber Sürücüsü, Mississauga",
    "about_badge_lbl": "Yıldır Hizmetinizdeyiz",
    "sec_about": "Hakkımızda",
    "title_about": "Gerçekten güvenebileceğiniz<br>bir firma",
    "desc_about_1": "North York'taki muhasebe firmamız, 2017'den beri bireylere ve işletmelere özverili ve kaliteli hizmet sunmaktadır.",
    "desc_about_2": "Girişimcilerin meşgul olduğunu biliyoruz. İşimiz sizin vergi ve defterlerinizi halletmek ki siz sadece işinizi büyütmeye odaklanın.",
    "about_comm": "Hizmet Verdiğimiz Topluluklar:",
    "btn_book_about": "Ücretsiz Randevu Al →",
    "sec_cont": "İletişim",
    "title_cont": "Bize İstediğiniz<br>Zaman Ulaşın",
    "cont_addr": "Ofis Adresi",
    "cont_phone": "Telefon",
    "cont_email": "E-posta",
    "cont_wa": "WhatsApp",
    "cont_pref_lang": "Tercih Edilen Dil:",
    "cont_box": "Bize Mesaj Gönderin",
    "cont_subj": "Konu",
    "cont_msg": "Mesajınız",
    "btn_send": "Mesajı Gönder →",
    "footer_rights": "© 2025 FaceAccounting.com — Tüm hakları saklıdır.",
    "footer_addr": "1110 Finch Ave W, Ünite 314, North York ON",
    "modal_title": "Randevu Onaylandı!",
    "modal_desc": "Teşekkürler. Randevu talebiniz başarıyla alındı. Detayları içeren bir e-posta onayı göndereceğiz.",
    "btn_done": "Tamam",
    "chat_title": "🤖 FaceTax Asistan",
    "chat_greet": "Merhaba! 👋 Ben Yapay Zeka Vergi Asistanınızım. Size nasıl yardımcı olabilirim?",
    "chat_q1": "Vergi Tarihleri?",
    "chat_q2": "HST Oranı?",
    "chat_q3": "Ücretler?",
    "chat_q4": "T1 İçin Gerekenler?"
  },
  sq: {
    "announce": "🍁 Sezoni i Taksave 2025 — Dorëzoni T1 para 30 Prillit.",
    "book_announce": "Rezervo takimin →",
    "nav_services": "Shërbimet",
    "nav_tools": "Mjetet",
    "nav_calc": "Llogaritësi i Taksave",
    "nav_about": "Rreth Nesh",
    "nav_contact": "Kontakt",
    "nav_book": "Rezervo",
    "hero_badge": "Të besuar në Toronto GTA që nga 2017",
    "hero_title": "<em>Zgjidhje të Shpejta</em><br>& Efektive të<br>Kontabilitetit",
    "hero_desc": "Shërbime profesionale kontabiliteti dhe taksash për individë dhe biznese në North York, Toronto dhe Montreal. Shërbejmë në Shqip, Anglisht, Turqisht dhe Boshnjakisht.",
    "btn_book_free": "📅 Rezervo Konsultë Falas",
    "btn_try_calc": "🧮 Provo Llogaritësin",
    "stat_exp": "Vite Përvojë",
    "stat_lang": "Gjuhë të Mbështetura",
    "stat_clients": "Klientë të Kënaqur",
    "card_personal": "Deklarata Taksash Personale",
    "card_personal_desc": "T1, T4, të vetëpunësuar, shoferë Uber, studentë dhe pensionistë.",
    "card_personal_tag": "Duke filluar nga $80",
    "card_biz": "Regjistrim Biznesi & Taksa Korporative",
    "card_biz_desc": "Inkorporim, regjistrim GST/HST, borderotë dhe deklaratat T2.",
    "card_biz_tag": "Konsultë Fillestare Falas",
    "card_multi": "Mbështetje Shumëgjuhëshe",
    "card_multi_desc": "Kemi kënaqësinë t'u shërbejmë komuniteteve Shqiptare në GTA.",
    "trust_cra": "Kontabilistë të<br>Çertifikuar",
    "trust_same": "Takime në<br>të njëjtën ditë",
    "trust_4lang": "Mbështetje në<br>4 Gjuhë",
    "trust_secure": "Portal i Sigurt<br>Dokumentesh",
    "trust_wa": "Mbështetje<br>WhatsApp",
    "sec_services": "Shërbimet Tona",
    "title_services": "Gjithçka që ju nevojitet,<br>nën një çati",
    "desc_services": "Nga deklaratat personale T1 tek inkorporimet e biznesit.",
    "serv_pers": "Shërbime Personale",
    "serv_pers_1": "I punësuar (T4)",
    "serv_pers_2": "I vetëpunësuar",
    "serv_pers_3": "Individ (T1)",
    "serv_pers_4": "Jo-rezidentë",
    "serv_pers_5": "Pensionistë",
    "serv_pers_6": "Student",
    "serv_pers_7": "Përfitues të Asistencës Sociale",
    "serv_pers_8": "Shofer Uber",
    "serv_bizreg": "Regjistrim Biznesi",
    "serv_bizreg_1": "Regjistrim Inkorporimi",
    "serv_bizreg_2": "Kërkim Emri Biznesi (NUANS)",
    "serv_bizreg_3": "Regjistrim Numri GST/HST",
    "serv_bizreg_4": "Regjistrim Borderoje",
    "serv_bizreg_5": "Biznes Individual",
    "serv_bizreg_6": "Mbyllje Biznesi",
    "serv_biz": "Shërbime Biznesi",
    "serv_biz_1": "Kontabilitet",
    "serv_biz_2": "Mbajtje e Librave",
    "serv_biz_3": "Tatim mbi të Ardhurat",
    "serv_biz_4": "Taksa e Korporatave (T2)",
    "serv_biz_5": "Menaxhim Borderoje",
    "serv_biz_6": "Kuti Postare Biznesi",
    "sec_tools": "Karakteristikat e Platformës",
    "title_tools": "Mjete të zgjuara për<br>kontabilitet të lehtë",
    "desc_tools": "Një platformë moderne me mjete që ju kursejnë kohë.",
    "badge_avail": "Në Dispozicion",
    "badge_updated": "I Përditësuar",
    "badge_new": "E re",
    "badge_soon": "Së Shpejti",
    "tool_book": "Rezervime Takimesh Online",
    "tool_book_desc": "Rezervoni një konsultë në çdo kohë.",
    "tool_calc": "Llogaritës Taksash",
    "tool_calc_desc": "Vlerësim i menjëhershëm i taksave tuaja.",
    "tool_chat": "Asistent Chat AI",
    "tool_chat_desc": "Bëni çdo pyetje rreth taksave 24/7.",
    "tool_gst": "Llogaritësi GST/HST",
    "tool_gst_desc": "Shtoni ose hiqni 13% HST menjëherë.",
    "tool_doc": "Portal i Sigurt Dokumentesh",
    "tool_doc_desc": "Ngarkoni T4, faturat në portalin tonë të enkriptuar.",
    "tool_remind": "Kujtesa e Afateve të CRA",
    "tool_remind_desc": "Mos humbisni asnjë datë aplikimi.",
    "sec_calc": "Llogaritësi i Taksave",
    "title_calc": "Vlerësoni deklaratën<br>tuaj të 2024",
    "desc_calc": "Merrni një vlerësim të shpejtë të taksës suaj të të ardhurave.",
    "calc_bullet_1": "Taksa Federale + Provinciale e Ontarios",
    "calc_bullet_2": "Zbritje personale bazë",
    "calc_bullet_3": "Të ardhura nga punësimi dhe vetëpunësimi",
    "calc_bullet_4": "Rezultate në sekonda, nuk kërkohet hyrje",
    "calc_box_title": "🧮 Vlerësim i Shpejtë i Taksave — 2024",
    "calc_lbl_income": "Të Ardhurat Vjetore (Bruto)",
    "calc_lbl_rrsp": "Kontributi RRSP ($)",
    "calc_lbl_cap": "Fitimet Kapitale ($)",
    "calc_lbl_emp": "Lloji i Punësimit",
    "emp_opt_1": "I punësuar (T4)",
    "emp_opt_2": "I vetëpunësuar",
    "emp_opt_3": "Shofer Uber",
    "calc_lbl_prov": "Provinca",
    "calc_res_lbl": "Taksa e Vlerësuar",
    "calc_res_note": "Norma efektive",
    "calc_cta_note": "Dëshironi numrin e saktë?",
    "gst_title": "📊 Llogaritësi i GST/HST i Ontarios",
    "gst_desc": "Shtoni ose nxirrni me shpejtësi 13% HST për faturat tuaja në Ontario.",
    "gst_amt": "Shuma ($)",
    "btn_add_hst": "Shto 13% HST",
    "btn_ext_hst": "Hiq 13% HST",
    "gst_sub": "Nëntotali:",
    "gst_tax": "HST (13%):",
    "gst_tot": "Totali:",
    "gst_biz_tag": "Për Bizneset",
    "gst_biz_title": "Faturimi u bë i<br>thjeshtë",
    "gst_biz_desc": "Nëse të ardhurat e biznesit tuaj tejkalojnë 30,000 $ duhet të regjistroheni për GST/HST.",
    "gst_biz_1": "Norma e HST në Ontario është 13%",
    "gst_biz_2": "Pjesa GST është 5%, Provinciale është 8%",
    "gst_biz_3": "Ne menaxhojmë deklarimet e GST/HST",
    "btn_gst_help": "Keni nevojë për ndihmë me regjistrimin? →",
    "sec_book": "Rezervime Online",
    "title_book": "Rezervoni takimin<br>tuaj në 60 sekonda",
    "desc_book": "Zgjidhni shërbimin tuaj, zgjidhni një orar të përshtatshëm dhe do ta konfirmojmë menjëherë.",
    "step_1_title": "Zgjidhni shërbimin",
    "step_1_desc": "T1, T2, kontabilitet, regjistrim biznesi etj.",
    "step_2_title": "Zgjidhni një orar",
    "step_2_desc": "E hënë–E shtunë, 9am–6pm.",
    "step_3_title": "Merrni konfirmim të menjëhershëm",
    "step_3_desc": "Email me adresën e zyrës ose linkun e videos dërgohet menjëherë.",
    "loc_title": "📍 Vendndodhja e Zyrës",
    "book_box_title": "📅 Kërkoni një Takim",
    "lbl_name": "Emri i Plotë",
    "lbl_phone": "Telefoni",
    "lbl_email": "Email",
    "lbl_serv": "Shërbimi i Nevojshëm",
    "lbl_date": "Data e Preferuar",
    "lbl_time": "Ora",
    "lbl_meet": "Lloji i Takimit",
    "btn_confirm": "Konfirmo Takimin →",
    "book_wa": "Ase na kontaktoni në WhatsApp",
    "sec_test": "Shqyrtimet e Klientëve",
    "title_test": "Të besuar nga<br>qindra në GTA",
    "desc_test": "Reagime të vërteta nga individë dhe pronarë biznesesh.",
    "test_1": "\"Deklaroj taksat T1 me Face Accounting prej 3 vitesh. Taksat e mia si i vetëpunësuar janë komplekse – gjithmonë më ofrojnë rimbursimin më të mirë.\"",
    "test_2": "\"U morën me inkorporimin, regjistrimin GST, dhe deklaratën e parë të korporatës. Gjithçka shkoi pa probleme.\"",
    "test_3": "\"Si shofer Uber nuk e dija si t'i deklaroja taksat saktë. Më shpjeguan gjithçka qartë!\"",
    "test_1_sub": "I vetëpunësuar, North York",
    "test_2_sub": "Pronar Biznesi, Toronto",
    "test_3_sub": "Shofer Uber, Mississauga",
    "about_badge_lbl": "Vite Shërbim në Toronto GTA",
    "sec_about": "Rreth Nesh",
    "title_about": "Një firmë që<br>mund ti besoni",
    "desc_about_1": "Firma jonë në North York ofron shërbime kontabiliteti dedikuar që nga 2017.",
    "desc_about_2": "Puna jonë është të merremi me taksat dhe kontabilitetin tuaj në mënyrë që ju të fokusoheni te biznesi juaj.",
    "about_comm": "Komunitetet që u shërbejmë:",
    "btn_book_about": "Rezervo Konsultë Falas →",
    "sec_cont": "Kontakt",
    "title_cont": "Na Kontaktoni<br>në çdo kohë",
    "cont_addr": "Adresa e Zyrës",
    "cont_phone": "Telefoni",
    "cont_email": "Email",
    "cont_wa": "WhatsApp",
    "cont_pref_lang": "Gjuha e Preferuar:",
    "cont_box": "Na Dërgoni një Mesazh",
    "cont_subj": "Subjekti",
    "cont_msg": "Mesazhi",
    "btn_send": "Dërgo Mesazhin →",
    "footer_rights": "© 2025 FaceAccounting.com — Të gjitha të drejtat e rezervuara.",
    "footer_addr": "1110 Finch Ave W, Njësia 314, North York ON",
    "modal_title": "Takimi i Konfirmuar!",
    "modal_desc": "Faleminderit. Takimi juaj është kërkuar me sukses. Së shpejti do t'ju dërgojmë një email konfirmimi me detaje.",
    "btn_done": "Në rregull",
    "chat_title": "🤖 FaceTax Asistent",
    "chat_greet": "Përshëndetje! 👋 Unë jam Asistenti i Taksave AI. Si mund t'ju ndihmoj?",
    "chat_q1": "Afati i Taksave?",
    "chat_q2": "Norma e HST?",
    "chat_q3": "Çmimet?",
    "chat_q4": "Kërkesat për T1?"
  },
  bs: {
    "announce": "🍁 Poreska sezona 2025 — Podnesite T1 prije 30. aprila.",
    "book_announce": "Zakažite termin →",
    "nav_services": "Usluge",
    "nav_tools": "Alati",
    "nav_calc": "Kalkulator Poreza",
    "nav_about": "O Nama",
    "nav_contact": "Kontakt",
    "nav_book": "Zakaži Termin",
    "hero_badge": "Od povjerenja u Torontu od 2017.",
    "hero_title": "<em>Brza i Efikasna</em><br>Računovodstvena<br>Rješenja",
    "hero_desc": "Profesionalne računovodstvene usluge i usluge oporezivanja za pojedince i firme u North Yorku, Torontu i Montrealu. Usluge pružamo na Bosanskom, Engleskom, Turskom i Albanskom.",
    "btn_book_free": "📅 Zakaži Besplatnu Konsultaciju",
    "btn_try_calc": "🧮 Probaj Kalkulator Poreza",
    "stat_exp": "Godina Iskustva",
    "stat_lang": "Podržanih Jezika",
    "stat_clients": "Zadovoljnih Klijenata",
    "card_personal": "Lične Poreske Prijave",
    "card_personal_desc": "T1, T4, samozaposleni, Uber vozači, nerezidenti, studenti i penzioneri.",
    "card_personal_tag": "Počevši od $80",
    "card_biz": "Registracija Firmi i Porez na Dobit",
    "card_biz_desc": "Osnivanje, GST/HST registracija, plate, T2 prijave i vođenje knjiga.",
    "card_biz_tag": "Besplatna Početna Konsultacija",
    "card_multi": "Višejezična Podrška",
    "card_multi_desc": "Pružamo usluge Bosanskoj zajednici u GTA bez jezičkih barijera.",
    "trust_cra": "CRA Certificirani<br>Računovođe",
    "trust_same": "Termini<br>Istog Dana",
    "trust_4lang": "Podrška na<br>4 Jezika",
    "trust_secure": "Siguran Portal za<br>Dokumente",
    "trust_wa": "WhatsApp<br>Podrška",
    "sec_services": "Naše Usluge",
    "title_services": "Sve što vam treba,<br>pod jednim krovom",
    "desc_services": "Od ličnih T1 prijava do prijava kompanija i registracije firmi — stručno računovodstvo za svaku fazu vašeg poslovanja.",
    "serv_pers": "Lične Usluge",
    "serv_pers_1": "Zaposleni (T4)",
    "serv_pers_2": "Samozaposleni",
    "serv_pers_3": "Pojedinci (T1)",
    "serv_pers_4": "Nerezidenti",
    "serv_pers_5": "Penzioneri",
    "serv_pers_6": "Studenti",
    "serv_pers_7": "Korisnici Socijalne Pomoći",
    "serv_pers_8": "Uber Vozači",
    "serv_bizreg": "Registracija Firmi",
    "serv_bizreg_1": "Registracija (Incorporation)",
    "serv_bizreg_2": "Pretraga Imena Firme (NUANS)",
    "serv_bizreg_3": "Registracija GST/HST Broja",
    "serv_bizreg_4": "Registracija Plata",
    "serv_bizreg_5": "Obrt (Sole Proprietorship)",
    "serv_bizreg_6": "Gašenje Firme",
    "serv_biz": "Poslovne Usluge",
    "serv_biz_1": "Računovodstvo",
    "serv_biz_2": "Vođenje Knjiga",
    "serv_biz_3": "Porez na Dohodak",
    "serv_biz_4": "Porez na Dobit (T2)",
    "serv_biz_5": "Upravljanje Platama",
    "serv_biz_6": "Poslovno Poštansko Sanduče",
    "sec_tools": "Funkcije Platforme",
    "title_tools": "Pametni alati za<br>lako računovodstvo",
    "desc_tools": "Moderna platforma sa alatima koji štede vrijeme.",
    "badge_avail": "Dostupno Sada",
    "badge_updated": "Ažurirano",
    "badge_new": "Novo",
    "badge_soon": "Uskoro",
    "tool_book": "Online Zakazivanje",
    "tool_book_desc": "Zakažite konsultaciju u bilo koje vrijeme.",
    "tool_calc": "Kalkulator Procjene Poreza",
    "tool_calc_desc": "Trenutna procjena vaših federalnih i provincijskih poreza Ontarija.",
    "tool_chat": "AI Chat Asistent",
    "tool_chat_desc": "Postavite porezna pitanja 24/7.",
    "tool_gst": "Kalkulator GST/HST",
    "tool_gst_desc": "Brzo dodajte ili oduzmite 13% GST/HST za fakture.",
    "tool_doc": "Siguran Portal",
    "tool_doc_desc": "Bezbijedno pošaljite dokumente preko našeg enkriptovanog portala.",
    "tool_remind": "CRA Podsjetnici za Rokove",
    "tool_remind_desc": "Nikad ne propustite rok za prijavu.",
    "sec_calc": "Kalkulator Poreza",
    "title_calc": "Procijenite povrat<br>poreza za 2024",
    "desc_calc": "Dobijte brzu procjenu svog poreza na dohodak.",
    "calc_bullet_1": "Federalni + Provincijski Porez",
    "calc_bullet_2": "Osnovni lični odbici",
    "calc_bullet_3": "Prihodi iz radnog odnosa i samozapošljavanja",
    "calc_bullet_4": "Rezultati u sekundi, nije potrebna prijava",
    "calc_box_title": "🧮 Brza Procjena Poreza — 2024",
    "calc_lbl_income": "Godišnji Prihod (Bruto)",
    "calc_lbl_rrsp": "RRSP Doprinos ($)",
    "calc_lbl_cap": "Kapitalni Dobici ($)",
    "calc_lbl_emp": "Vrsta Zaposlenja",
    "emp_opt_1": "Zaposleni (T4)",
    "emp_opt_2": "Samozaposleni",
    "emp_opt_3": "Uber Vozač",
    "calc_lbl_prov": "Provincija",
    "calc_res_lbl": "Procijenjeni Dug Poreza",
    "calc_res_note": "Efektivna stopa",
    "calc_cta_note": "Želite tačan broj?",
    "gst_title": "📊 Kalkulator GST/HST Ontarija",
    "gst_desc": "Brzo dodajte ili oduzmite 13% HST za vaše fakture ili račune u Ontariju.",
    "gst_amt": "Iznos ($)",
    "btn_add_hst": "Dodaj 13% HST",
    "btn_ext_hst": "Oduzmi 13% HST",
    "gst_sub": "Međuzbir:",
    "gst_tax": "HST (13%):",
    "gst_tot": "Ukupno:",
    "gst_biz_tag": "Za Firme",
    "gst_biz_title": "Lako<br>Fakturisanje",
    "gst_biz_desc": "Ako prihodi vaše firme premašuju $30,000, morate se registrovati za GST/HST.",
    "gst_biz_1": "Stopa HST u Ontariju je 13%",
    "gst_biz_2": "GST je 5%, provincijski dio je 8%",
    "gst_biz_3": "Mi vodimo vaše GST/HST prijave",
    "btn_gst_help": "Trebate pomoć oko registracije? →",
    "sec_book": "Online Zakazivanje",
    "title_book": "Zakažite termin<br>za 60 sekundi",
    "desc_book": "Odaberite svoju uslugu, vrijeme i mi ćemo odmah potvrditi.",
    "step_1_title": "Odaberite uslugu",
    "step_1_desc": "T1, T2, vođenje knjiga, registracija firme i još mnogo toga.",
    "step_2_title": "Izaberite vrijeme",
    "step_2_desc": "Pon–Sub, 9am–6pm. Često dostupni termini isti dan.",
    "step_3_title": "Odmah dobijte potvrdu",
    "step_3_desc": "Potvrdni email s adresom kancelarije ili linkom za video poziv se odmah šalje.",
    "loc_title": "📍 Lokacija Kancelarije",
    "book_box_title": "📅 Zatražite Termin",
    "lbl_name": "Ime i Prezime",
    "lbl_phone": "Telefon",
    "lbl_email": "Email",
    "lbl_serv": "Potrebna Usluga",
    "lbl_date": "Željeni Datum",
    "lbl_time": "Vrijeme",
    "lbl_meet": "Vrsta Sastanka",
    "btn_confirm": "Potvrdi Termin →",
    "book_wa": "Ili nas kontaktirajte na WhatsApp",
    "sec_test": "Iskustva Klijenata",
    "title_test": "Stotine klijenata u<br>Torontu nam vjeruju",
    "desc_test": "Stvarne povratne informacije pojedinaca i vlasnika firmi.",
    "test_1": "\"Svoju T1 prijavu podnosim preko Face Accounting-a već 3 godine. Moji porezi kao samozaposlenog su komplikovani — oni mi uvijek osiguraju najbolji povrat.\"",
    "test_2": "\"Oni su obavili osnivanje naše firme, GST registraciju i prvu prijavu korporativnog poreza. Sve je bilo brzo i profesionalno!\"",
    "test_3": "\"Kao Uber vozač nisam znao kako pravilno prijaviti porez. Face Accounting je objasnio sve jasno i prijavio sve na vrijeme. Topla preporuka!\"",
    "test_1_sub": "Samozaposleni, North York",
    "test_2_sub": "Vlasnik Firme, Toronto",
    "test_3_sub": "Uber Vozač, Mississauga",
    "about_badge_lbl": "Godina Usluga u Torontu GTA",
    "sec_about": "O Nama",
    "title_about": "Firma kojoj zaista<br>možete vjerovati",
    "desc_about_1": "Naša firma u North Yorku pruža posvećene i kvalitetne računovodstvene usluge pojedincima i preduzećima od 2017.",
    "desc_about_2": "Mi razumijemo da su poduzetnici zauzeti. Naš posao je da obradimo vaše poreze i knjigovodstvo kako biste vi mogli rasti.",
    "about_comm": "Zajednice kojima ponosno služimo:",
    "btn_book_about": "Zakaži Besplatnu Konsultaciju →",
    "sec_cont": "Kontakt",
    "title_cont": "Stupite u kontakt<br>bilo kada",
    "cont_addr": "Adresa Kancelarije",
    "cont_phone": "Telefon",
    "cont_email": "Email",
    "cont_wa": "WhatsApp",
    "cont_pref_lang": "Željeni Jezik:",
    "cont_box": "Pošaljite nam poruku",
    "cont_subj": "Tema",
    "cont_msg": "Poruka",
    "btn_send": "Pošalji Poruku →",
    "footer_rights": "© 2025 FaceAccounting.com — Sva prava zadržana.",
    "footer_addr": "1110 Finch Ave W, Unit 314, North York ON",
    "modal_title": "Termin Potvrđen!",
    "modal_desc": "Hvala. Vaš termin je uspješno zakazan. Uskoro ćemo vam poslati potvrdni email sa detaljima.",
    "btn_done": "U redu",
    "chat_title": "🤖 FaceTax Asistent",
    "chat_greet": "Pozdrav! 👋 Ja sam Vaš AI Poreski Asistent. Kako vam mogu pomoći?",
    "chat_q1": "Poreski Rokovi?",
    "chat_q2": "Stopa HST?",
    "chat_q3": "Cijene?",
    "chat_q4": "Zahtjevi za T1?"
  }
};
